# Format goes like this
# trainer_name:
#   k: v

name: overcooked
mode: full_divider_broccoli_large_upper_random_init
horizon: 40
recipes: [
  "TomatoOnionSalad",
  "OnionTomatoSalad",
  "TomatoCarrotSalad",
  "CarrotTomatoSalad",
  "TomatoBroccoliSalad",
  "BroccoliTomatoSalad",

  "LettuceOnionSalad",
  "OnionLettuceSalad",
  "LettuceCarrotSalad",
  "CarrotLettuceSalad",
  "LettuceBroccoliSalad",
  "BroccoliLettuceSalad",

  "PotatoOnionSalad",
  "OnionPotatoSalad",
  "PotatoCarrotSalad",
  "CarrotPotatoSalad",
  "PotatoBroccoliSalad",
  "BroccoliPotatoSalad",
]
obs_spaces: dense_partial
obs_range: 8
num_agents: 2
interact_reward: 0.5
progress_reward: 1.0
complete_reward: 10.0
step_cost: 0.2
#display: True
